# Generated by Django 5.2.16 on 2026-07-27 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('citizenship_number', 'Citizenship Number'), ('license_number', 'License Number'), ('address', 'Address'), ('date_of_birth', 'Date of Birth')], max_length=50)),
                ('current_value', models.CharField(blank=True, max_length=255)),
                ('requested_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='correction_documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Request',
                'verbose_name_plural': 'Correction Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
