# Generated by Django 5.2.16 on 2026-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_correctionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='field_name',
            field=models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('citizenship_number', 'Citizenship Number'), ('nid_number', 'National ID (NID)'), ('license_number', 'License Number'), ('address', 'Address'), ('date_of_birth', 'Date of Birth')], max_length=50),
        ),
    ]
