# Generated by Django 5.2.16 on 2026-07-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nid_number_alter_correctionrequest_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentCitizenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('citizenship_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nid_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='Kathmandu, Nepal')),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='accounts.governmentcitizenrecord'),
        ),
    ]
