# Generated by Django 5.2.16 on 2026-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_governmentcitizenrecord_user_citizen_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentcitizenrecord',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
