# Generated by Django 6.0.7 on 2026-07-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('car', 'Car'), ('jeep', 'Jeep/SUV'), ('van', 'Van'), ('bus', 'Bus'), ('truck', 'Truck'), ('tempo', 'Tempo'), ('auto_rickshaw', 'Auto Rickshaw'), ('other', 'Other')], default='motorcycle', max_length=20)),
                ('make', models.CharField(help_text='Manufacturer (e.g. Honda, Tata)', max_length=50)),
                ('model', models.CharField(help_text='Model name (e.g. Dio, Nexon)', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('bluebook_number', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
