# Generated by Django 6.0.7 on 2026-07-17 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Info_Requested', 'Information Requested')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='bluebook_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_ownerships', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_ownerships', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bluebook_front_image', models.ImageField(upload_to='vehicle_docs/')),
                ('bluebook_back_image', models.ImageField(upload_to='vehicle_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Documents',
            },
        ),
    ]
