# Generated by Django 6.0.7 on 2026-07-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('parking', 'Parking Area'), ('no_parking', 'No Parking Zone'), ('construction', 'Road Construction'), ('diversion', 'Traffic Diversion'), ('accident', 'Accident'), ('traffic_light', 'Traffic Light'), ('checkpoint', 'Checkpoint'), ('hospital', 'Hospital'), ('fuel_station', 'Fuel Station'), ('road_closure', 'Road Closure'), ('speed_zone', 'Speed Zone')], max_length=15)),
                ('gps_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('official', 'Official (Officer)'), ('community', 'Community Report')], default='official', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_locations', to=settings.AUTH_USER_MODEL)),
                ('community_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_location', to='reports.communityreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
