# Generated by Django 5.2.16 on 2026-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='appeal_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of times appeal has been submitted/reviewed'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('final_rejected', 'Final Rejected')], default='pending', max_length=20),
        ),
    ]
