# Generated by Django 6.0.7 on 2026-07-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. NO_HELMET', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('dangerous', 'Dangerous')], default='minor', max_length=10)),
                ('base_fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Violation Type',
                'verbose_name_plural': 'Violation Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_number', models.PositiveIntegerField(help_text='Which offense this rule applies to (1 = first, 2 = second, etc.)')),
                ('time_window_days', models.PositiveIntegerField(default=180, help_text='Time window in days to count previous offenses (e.g. 180 = 6 months)')),
                ('action', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('increased_fine', 'Increased Fine'), ('license_suspension', 'License Suspension')], max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fine amount for this tier. 0 for warnings.', max_digits=10)),
                ('is_immediate', models.BooleanField(default=False, help_text='If True, skip offense counting — always apply this action.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='violations.violationtype')),
            ],
            options={
                'verbose_name': 'Traffic Rule',
                'verbose_name_plural': 'Traffic Rules',
                'ordering': ['violation_type', 'offense_number'],
                'unique_together': {('violation_type', 'offense_number')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine')], max_length=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('officer_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations_received', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_issued', to=settings.AUTH_USER_MODEL)),
                ('rule_applied', models.ForeignKey(blank=True, help_text='The traffic rule that was applied by the rule engine.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.trafficrule')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='vehicles.vehicle')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_change', models.IntegerField(help_text='Positive or negative delta')),
                ('reason', models.CharField(max_length=255)),
                ('previous_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_score_history', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.violation')),
            ],
            options={
                'verbose_name_plural': 'Safety Score History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='This is a formal warning. Repeated offenses will result in a fine.')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='violations.violation')),
            ],
        ),
    ]
