# Generated by Django 6.0.7 on 2026-07-17 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='violations.violation')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
