# Generated by Django 6.0.7 on 2026-07-17 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrule',
            name='action',
            field=models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('increased_fine', 'Increased Fine'), ('license_suspension', 'License Suspension'), ('community_service', 'Community Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='violation',
            name='action_taken',
            field=models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('community_service', 'Community Service')], max_length=20),
        ),
        migrations.CreateModel(
            name='CommunityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_hours', models.PositiveIntegerField()),
                ('completed_hours', models.PositiveIntegerField(default=0)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_services', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_service', to='violations.violation')),
            ],
        ),
    ]
