# Generated by Django 6.0.7 on 2026-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_alter_trafficrule_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationtype',
            name='score_deduction',
            field=models.PositiveIntegerField(default=0, help_text='Points to deduct from driver score'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='category',
            field=models.CharField(choices=[('educational', 'Level 1 - Educational'), ('moderate', 'Level 2 - Moderate'), ('dangerous', 'Level 3 - Dangerous'), ('critical', 'Level 4 - Critical')], default='educational', max_length=15),
        ),
    ]
